#!/usr/bin/env bash
# This script manages the manage_my_process script

MANAGE_SCRIPT="./manage_my_process"

case "$1" in
    start)
        sudo $MANAGE_SCRIPT start
        ;;
    stop)
        sudo $MANAGE_SCRIPT stop
        ;;
    restart)
        sudo $MANAGE_SCRIPT restart
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

exit 0
