#!/usr/bin/env bash
# This script displays the PID and process name of processes containing the word "bash"

for pid in /proc/[0-9]*
do
    if [ -d "$pid" ] && [ -r "$pid/comm" ]; then
        pname=$(<"$pid/comm")
        if [[ "$pname" == *bash* ]]; then
            echo "$(basename "$pid") $pname"
        fi
    fi
done
